const student = {
  id: '',
  documentId: '',
  firstName: 'Nombre',
  lastName: 'Apellido',
  dateOfBirth: '',
  email: '',
  gender: '',
  address: '',
  countryOfBirth: '',
  cityOfBirth: '',
  phone: '',
  mobilePhone: '',
  height: '',
  weight: '',
  foundOut: '',
  medicalConditions: '',
  giSize: '',
  plan: {
    id: '',
    code: '',
    description: '',
    price: '',
  },
  rank: {
    id: '',
    code: '',
    description: 'Blanco',
    imagePath: '',
  },
  methodOfPayment: {
    id: '',
    code: '',
    description: 'Efectivo',
  },
  isActive: '',
  registrationDate: '05-10-2017',
  enrollmentDate: '25-10-2017',
  trialEnd: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  legalGuardianName: '',
  legalGuardianPhone: '',
  maritalStatus: {
    id: '',
    code: '',
    description: '',
  },
};

export default student;
