const student = {
  id: '',
  documentId: '',
  firstName: '',
  lastName: '',
  dateOfBirth: '',
  email: '',
  gender: '',
  address: '',
  countryOfBirth: '',
  cityOfBirth: '',
  phone: '',
  mobilePhone: '',
  height: '',
  weight: '',
  foundOut: '',
  medicalConditions: '',
  giSize: '',
  planId: '',
  rankId: '',
  methodOfPaymentId: '',
  isActive: '',
  registrationDate: '',
  enrollmentDate: '',
  trialEnd: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  legalGuardianName: '',
  legalGuardianPhone: '',
  maritalStatusId: '',
};

export default student;
